[project]
name = "refelction-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "black>=26.5.1",
    "deepseek>=1.0.0",
    "grandalf>=0.8",
    "isort>=9.0.1",
    "langchain>=1.4.2",
    "langchain-openai>=1.6.5",
    "langchain-openapi>=0.1.1",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.12",
    "python-dotenv>=1.2.3",
]
